### ISSUE TITLE
Demo hangs

### ISSUE THREAD

**Issue by michaelschulte** [MCWillemsen/mouselabWEB20#1]
the demo http://www.mouselabweb.org/MLWEB20demo/gamble.php?subject=test&condnum=0
does not seem to work on Chrome and Safari (on OSX)
- update: it works in some randomisations but not others - after reloading through the different version, some work ... 

first demo seems to be fine.

**Comment by MCWillemsen** [comment]
does it help to refresh the page? there seems to be a problem that in some cases the boxes are not initialized as the page is loaded: have not been able to fix that issue... (something to do with putting event handlers on objects that have not been created yet...)

**Comment by michaelschulte** [comment]
yep - it happens in some versions (after refresh) but not others ...

**Comment by MCWillemsen** [comment]
I might have resolved it in the demo, can you check?

**Comment by michaelschulte** [comment]
check ~10 iterations - works :)

**Comment by michaelschulte** [comment]
followup: this is not fixed in the repo yet - correct? I see the same problem there ...

**Comment by MCWillemsen** [comment]
correct, it was not yet corrected in the repository. I have now pushed the fix directly to the master branch.
